#The user will manually need to validate the SSL certificate

AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  RootDomainName:
    Type: String
    Default: "militaryawardwriter.com"

Resources:
  # SSL Certificate
  MyCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref RootDomainName
      ValidationMethod: DNS
      SubjectAlternativeNames:
        - !Sub www.${RootDomainName}
      Tags:
        - Key: Name
          Value: MyCertificate

#create s3 bucket output bucket name

  RootBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref RootDomainName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false    
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  WWWBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub www.${RootDomainName}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false   
      WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: error.html
    UpdateReplacePolicy: Retain

  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: "2010-09-09"
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref RootBucket
                - /*
      Bucket: !Ref RootBucket

  # DNS Records in Route 53
  DNSRecordRoot:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: "Z057381329QIYL3F9NOJS"
      Name: !Ref RootDomainName
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2 # CloudFront Hosted Zone ID
        DNSName: !GetAtt CloudFrontDistribution.DomainName

  DNSRecordWWW:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: "Z057381329QIYL3F9NOJS"
      Name: !Sub www.${RootDomainName}
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2 # CloudFront Hosted Zone ID
        DNSName: !GetAtt CloudFrontDistribution.DomainName
  # CloudFront Distribution
  CloudFrontDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: !Sub ${RootDomainName}.s3-website-us-east-1.amazonaws.com
          Id: S3WebsiteOrigin            
          CustomOriginConfig:
            HTTPPort: 80
            HTTPSPort: 443
            OriginProtocolPolicy: http-only
        DefaultCacheBehavior:
          TargetOriginId: S3WebsiteOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - HEAD
            - DELETE
            - POST
            - GET
            - OPTIONS
            - PUT
            - PATCH
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        ViewerCertificate:
          AcmCertificateArn: !Ref MyCertificate
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2018
        Aliases:
          - !Ref RootDomainName
          - !Sub www.${RootDomainName}
        Enabled: true

Outputs:
  WebsiteURL:
    Value: !GetAtt RootBucket.WebsiteURL
    Description: "URL for website hosted on S3"
  DistributionDomainName:
    Value: !GetAtt CloudFrontDistribution.DomainName
    Description: "The domain name of the CloudFront distribution"
